[project]
name = "benasque-heat-daylength"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dask>=2026.8.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "netcdf4>=1.7.4",
    "pandas>=3.0.6",
    "xarray>=2026.7.0",
]

[project.scripts]
benasque-heat-daylength = "benasque_heat_daylength:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
